# based on https://github.com/jupyter/docker-stacks/blob/main/.github/actions/load-image/action.yml
name: Load Docker image
description: Download the image tar and load it to Docker

inputs:
  image:
    description: Image name
    required: true
  variant:
    description: Variant tag prefix
    required: true

runs:
  using: composite
  steps:
    - name: Download built image 📥
      uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.image }}--${{ inputs.variant }}
        path: /tmp/a2s/images/
    - name: Load downloaded image to docker 📥
      run: |
        zstd --uncompress --stdout --rm /tmp/a2s/images/${{ inputs.image }}--${{ inputs.variant }}.tar.zst | docker load
        docker image ls --all
      shell: bash
