name: Download a parent image, build a new one, and test it; then upload the image, tags, and manifests to GitHub artifacts

env:
  REGISTRY: quay.io
  OWNER: ${{ github.repository_owner }}

on:
  workflow_call:
    inputs:
      parent-image:
        description: Parent image name
        required: true
        type: string
      parent-variant:
        description: Parent variant tag prefix
        required: false
        type: string
        default: default
      image:
        description: Image name
        required: true
        type: string
      variant:
        description: Variant tag prefix
        required: false
        type: string
        default: default
      push:
        description: Publish image to registry
        type: boolean
        required: false
        default: false
      runs-on:
        description: GitHub Actions Runner image
        required: true
        type: string

jobs:
  build-test-upload:
    runs-on: ${{ inputs.runs-on }}

    steps:
      # Image with CUDA needs extra disk space
      - name: Free disk space 🧹
        if: contains(inputs.variant, 'cuda')
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: false
          android: true
          dotnet: true
          haskell: true
          large-packages: false
          docker-images: false
          swap-storage: false

      - name: Checkout Repo ⚡️
        uses: actions/checkout@v4

      # Self-hosted runners share a state (whole VM) between runs
      # Also, they might have running or stopped containers,
      # which are not cleaned up by `docker system prune`
      - name: Reset docker state and cleanup artifacts 🗑️
        run: |
          docker kill $(docker ps --quiet) || true
          docker rm $(docker ps --all --quiet) || true
          docker system prune --all --force
          rm -rf /tmp/a2s/
        shell: bash
      
      - name: Load parent image to Docker 📥
        if: inputs.parent-image != ''
        uses: ./.github/actions/load-image
        with:
          image: ${{ inputs.parent-image }}
          variant: ${{ inputs.parent-variant }}

      # Source/initial image is always based on jupyter/pytorch-notebook
      - name: Pull source image 📥
        if: inputs.parent-image == ''
        run: docker pull quay.io/jupyter/${{ inputs.image }}:${{ inputs.variant }}
        shell: bash

      - name: Build base image 🛠
        if: contains(inputs.image, 'base-gpu-notebook')
        run: | 
          # generate dockerfile
          cd base-gpu-notebook && bash generate_dockerfile.sh && cd ..
          # build docker
          docker build --rm --force-rm --tag ${{ env.REGISTRY }}/${{ env.OWNER }}/${{ inputs.image }}:${{ inputs.variant }} ${{ inputs.image }}/.build/${{ inputs.variant != 'default' && inputs.variant || '.' }}/ --build-arg REGISTRY=${{ env.REGISTRY }} --build-arg OWNER=${{ env.OWNER }}
        env:
          DOCKER_BUILDKIT: 1
          # Full logs for CI build
          BUILDKIT_PROGRESS: plain
        shell: bash

      - name: Build image 🛠
        if: inputs.parent-image != ''
        run: docker build --rm --force-rm --tag ${{ env.REGISTRY }}/${{ env.OWNER }}/${{ inputs.image }}:${{ inputs.variant }} ${{ inputs.image }}/${{ inputs.variant != 'default' && inputs.variant || '.' }}/ --build-arg REGISTRY=${{ env.REGISTRY }} --build-arg OWNER=${{ env.OWNER }}
        env:
          DOCKER_BUILDKIT: 1
          # Full logs for CI build
          BUILDKIT_PROGRESS: plain
        shell: bash

      - name: Save source image as a tar for later use 💾
        if: inputs.parent-image == ''
        run: |
          mkdir -p /tmp/a2s/images/
          docker save quay.io/jupyter/${{ inputs.image }}:${{ inputs.variant }} | zstd > /tmp/a2s/images/${{ inputs.image }}--${{ inputs.variant }}.tar.zst
        shell: bash

      - name: Save image as a tar for later use 💾
        if: inputs.parent-image != ''
        run: |
          mkdir -p /tmp/a2s/images/
          docker save ${{ env.REGISTRY }}/${{ env.OWNER }}/${{ inputs.image }}:${{ inputs.variant }} | zstd > /tmp/a2s/images/${{ inputs.image }}--${{ inputs.variant }}.tar.zst
        shell: bash

      - name: Upload image as artifact 💾
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.image }}--${{ inputs.variant }}
          path: /tmp/a2s/images/${{ inputs.image }}--${{ inputs.variant }}.tar.zst
          retention-days: 3

  images-tag-push:
    needs: [build-test-upload] 
    uses: ./.github/workflows/docker-tag-push.yml
    if: inputs.push == true
    with:
      image: ${{ inputs.image }}
      variant: ${{ inputs.variant }}
    secrets:
      REGISTRY_USERNAME: ${{ secrets.QUAY_USERNAME }}
      REGISTRY_TOKEN: ${{ secrets.QUAY_ROBOT_TOKEN }}

