name: Download a parent image, build a new one, and test it; then upload the image, tags, and manifests to GitHub artifacts

env:
  OWNER: ${{ github.repository_owner }}

on:
  workflow_call:
    inputs:
      parent-image:
        description: Parent image name
        required: true
        type: string
      parent-variant:
        description: Parent variant tag prefix
        required: false
        type: string
        default: default
      image:
        description: Image name
        required: true
        type: string
      variant:
        description: Variant tag prefix
        required: false
        type: string
        default: default
      context:
        description: Path to Dockerfile location
        required: false
        type: string
        default: default
      registry:
        description: Registry
        required: false
        type: string
        default: quay.io
      push:
        description: Publish image to registry
        type: boolean
        required: false
        default: false
      runs-on:
        description: GitHub Actions Runner image
        required: true
        type: string

jobs:
  build-test-upload:
    runs-on: ${{ inputs.runs-on }}

    steps:
      # Image with CUDA needs extra disk space
      - name: Free disk space 🧹
        if: contains(inputs.variant, 'cuda')
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: false
          android: true
          dotnet: true
          haskell: true
          large-packages: false
          docker-images: false
          swap-storage: false

      - name: Checkout Repo ⚡️
        uses: actions/checkout@v4

      # Self-hosted runners share a state (whole VM) between runs
      # Also, they might have running or stopped containers,
      # which are not cleaned up by `docker system prune`
      - name: Reset docker state and cleanup artifacts 🗑️
        run: |
          docker kill $(docker ps --quiet) || true
          docker rm $(docker ps --all --quiet) || true
          docker system prune --all --force
          rm -rf /tmp/a2s/
        shell: bash
      
      - name: Login to ghcr.io
        if: ${{ inputs.registry == 'ghcr.io' }}
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.GH_USERNAME }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Login to Quay Container Registry
        if: ${{ inputs.registry == 'quay.io' }}
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_ROBOT_TOKEN }}

      - name: Load parent image to Docker 📥
        if: inputs.parent-image != ''
        uses: ./.github/actions/load-image
        with:
          image: ${{ inputs.parent-image }}
          variant: ${{ inputs.parent-variant }}

      # Source/initial image is always based on jupyter/pytorch-notebook
      - name: Pull source image 📥
        if: inputs.parent-image == ''
        run: docker pull quay.io/jupyter/${{ inputs.image }}:${{ inputs.variant }}
        shell: bash

      - name: Generate base image Dockerfile
        if: contains(inputs.image, 'base-gpu-notebook')
        run: | 
          # generate dockerfile
          cd base-gpu-notebook && bash generate_dockerfile.sh && cd ..

      - name: Build image 🛠
        if: inputs.parent-image != ''
        id: build_image
        uses: docker/build-push-action@v5
        with:
          context: ${{ inputs.context }} 
          push: ${{ inputs.push }}
          tags: ${{ inputs.registry }}/${{ env.OWNER }}/${{ inputs.image }}:${{ inputs.variant }}

      - name: Save source image as a tar for later use 💾
        if: inputs.parent-image == ''
        run: |
          mkdir -p /tmp/a2s/images/
          docker save quay.io/jupyter/${{ inputs.image }}:${{ inputs.variant }} | zstd > /tmp/a2s/images/${{ inputs.image }}--${{ inputs.variant }}.tar.zst
        shell: bash

      - name: Save image as a tar for later use 💾
        if: inputs.parent-image != ''
        run: |
          mkdir -p /tmp/a2s/images/
          docker save ${{ inputs.registry }}/${{ env.OWNER }}/${{ inputs.image }}:${{ inputs.variant }} | zstd > /tmp/a2s/images/${{ inputs.image }}--${{ inputs.variant }}.tar.zst
        shell: bash

      - name: Upload image as artifact 💾
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.image }}--${{ inputs.variant }}
          path: /tmp/a2s/images/${{ inputs.image }}--${{ inputs.variant }}.tar.zst
          retention-days: 3
