name: Manual workflow
on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Image to build'
        required: true
        default: 'gpu-notebook'

jobs:
  setup:
    name: Setup 
    runs-on: ubuntu-latest

    outputs:
      owner: ${{ steps.setup_image.outputs.owner }}

    steps:
    - uses: actions/checkout@v2

    - name: Setup image
      id: setup_image
      run: |
        if [ "$GITHUB_EVENT_NAME" = "pull_request" ]
        then
          GH_BRANCH=$GITHUB_BASE_REF
        else
          GH_BRANCH=${GITHUB_REF##*/}
        fi

        echo "::set-output name=owner::ghcr.io/b-it-bots/docker"

  publish-gpu-notebook:
    name: Build and publish gpu-notebook
    if: github.event.inputs.branch == 'gpu-notebook'
    needs: setup
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GH_TOKEN }}

    - name: Build and deploy image
      id: build_and_deploy_image
      run: |
        OWNER=${{ needs.setup.outputs.owner }}

        bash build_and_publish.sh --registry ghcr.io --publish "all" --image gpu-notebook

    - name: Docker image list
      run: docker images

